spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cyberSec1
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

server:
  port: ${SERVER_PORT:8080}